name: Build Telegram Bot API (Debian 12)

on:
    workflow_dispatch:
        inputs:
            version_tag:
                description: 'Binary untuk Debian 12 Bookworm'
                required: true
                default: 'v1.0.0'

permissions:
    contents: write

jobs:
    build-binary:
        runs-on: ubuntu-latest
        container: debian:12

        steps:
            - name: 📦 Update OS & Install Build Dependencies
              run: |
                  apt-get update
                  apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev zip

            - name: 📥 Clone Source Code dari Telegram (TDLib)
              run: |
                  git clone --recursive https://github.com/tdlib/telegram-bot-api.git src

            - name: ⚙️ Compile Binary (Menggunakan Clang & batas -j2 agar tidak OOM)
              run: |
                  cd src
                  mkdir build && cd build
                  export CC=clang
                  export CXX=clang++
                  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../../out ..
                  cmake --build . --target install -j2

            - name: 🚀 Upload Binary sebagai Artifact Sementara
              uses: actions/upload-artifact@v4
              with:
                  name: telegram-bot-api-debian12
                  path: out/bin/telegram-bot-api

    release-binary:
        needs: build-binary
        runs-on: ubuntu-latest
        steps:
            - name: 📥 Download Artifact
              uses: actions/download-artifact@v4
              with:
                  name: telegram-bot-api-debian12
                  path: release-asset

            - name: 🗜️ Archive Binary (.zip)
              run: |
                  cd release-asset
                  chmod +x telegram-bot-api
                  zip telegram-bot-api-debian12.zip telegram-bot-api

            - name: 🎉 Publish to GitHub Releases
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.event.inputs.version_tag }}
                  name: Release ${{ github.event.inputs.version_tag }} (Debian 12)
                  body: 'Pre-compiled Telegram Bot API Server untuk OS Debian 12 (Bookworm).'
                  draft: false
                  prerelease: false
                  files: release-asset/telegram-bot-api-debian12.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  
