name: Build Telegram Bot API (Debian 12)

on:
    workflow_dispatch:

jobs:
    build-binary:
        runs-on: ubuntu-latest
        container: debian:12

        steps:
            - name: 📦 Update OS & Install Build Dependencies
              run: |
                  apt-get update
                  apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev

            - name: 📥 Clone Source Code dari Telegram (TDLib)
              run: |
                  git clone --recursive https://github.com/tdlib/telegram-bot-api.git src

            - name: ⚙️ Compile Binary (Proses ini memakan waktu ~15-20 menit)
              run: |
                  cd src
                  mkdir build && cd build
                  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../../out ..
                  cmake --build . --target install -j$(nproc)

            - name: 🚀 Upload Binary sebagai Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: telegram-bot-api-debian12
                  path: out/bin/telegram-bot-api
                  
